### ISSUE TITLE
Splits by words, not by lines

### ISSUE THREAD

**Issue by illus0r** [Volorf/Paster#4]
Thanks for you efforts!

![image](https://cloud.githubusercontent.com/assets/797993/24709080/7597518c-1a21-11e7-9384-d32ae42ed76c.png)

Expected:
![image](https://cloud.githubusercontent.com/assets/797993/24709158/afa7daf4-1a21-11e7-8cc9-997f5a073720.png)

Gives:
![image](https://cloud.githubusercontent.com/assets/797993/24709087/7eff2146-1a21-11e7-8bbe-0b4c737fd696.png)

**Comment by richardsison** [comment]
I hope this does get implemented soon… It's almost useless to me for it to break on spaces.

**Comment by richardsison** [comment]
@Volorf Any plans to update this?

**Comment by Volorf** [comment]
@richardsison Oh, sorry for a delay. I will fix it on Saturday. Thanks!

**Comment by Volorf** [comment]
Finally, I fixed all this stuff :)
